### ISSUE TITLE
Does forest supports pseudo classes?

### ISSUE THREAD

**Issue by kiddkai** [mhallin/forest#1]
Hi @mhallin ,

Thanks for creating this module. I just start integrate it with my project. I have a dumb question.
So after I did.

``` clj
(defstylesheet testing
    [.my-class-name {:color "#FFF"}])
```

Everything works fine.

But when I trying to add a new one which adds `:hover`:

``` clj
(defstylesheet testing
    [.my-class-name {:color "#FFF"}]
    [.my-class-name:hover {:color "#F00"}])
```

It compiled, but I got a new class name in the `<style>` tag instead of using the `:hover`:

``` css
.{{ prefix }}-my-class-name {
   ...
}
.{{ prefis }}_my-class-name_hover {
   ...
}
```

Thanks

**Comment by mhallin** [comment]
This has been implemented in release 0.1.4 thanks to your pull request.
